# Use gcc base image
FROM gcc:15.1.0

# Install dependencies for building and testing
RUN apt-get update && apt-get install -y cmake gdb && rm -rf /var/lib/apt/lists/*

# Copy source code
COPY . /usr/src/Server
WORKDIR /usr/src/Server

# Build the project
RUN if [ -d "/usr/src/Server/build" ]; then rm -rf /usr/src/Server/build; fi && mkdir /usr/src/Server/build
WORKDIR /usr/src/Server/build
RUN cmake .. && make

# Run tests
CMD ["./ServerTests"]