# Use gcc base image
FROM gcc:15.1.0

# Install only runtime dependencies (if needed)
RUN apt-get update && apt-get install -y cmake && rm -rf /var/lib/apt/lists/*

# Copy source code
COPY . /usr/src/Server
WORKDIR /usr/src/Server

# Build the project
# Remove the existing build directory if it exists, then create a new one
RUN if [ -d "/usr/src/Server/build" ]; then rm -rf /usr/src/Server/build; fi && mkdir /usr/src/Server/build

# Set the working directory to the newly created build directory
WORKDIR /usr/src/Server/build

# Install build dependencies
RUN cmake .. && make

# Mount a volume for data
VOLUME [ "/usr/src/Server/build/data" ]

# Set working directory to build output
WORKDIR /usr/src/Server/build
# Run the compiled binary
ENTRYPOINT [ "./ServerExecutable" ]
