services:
  server:
    container_name: "approject_server"
    build:
      context: ./src/Server
      dockerfile: Dockerfile.server
    tty: true
    stdin_open: true
    volumes:
      - ./data/:/usr/src/Server/build/data


  client:
    container_name: "approject_client"
    build:
      context: ./src/Client
      dockerfile: Dockerfile.client
    tty: true
    stdin_open: true
  tests:
    build:
      context: ./src/Server
      dockerfile: Dockerfile.tests