services:
  blacklist_server:
    container_name: "blacklist_server"
    build:
      context: ./src/BlacklistServer
      dockerfile: Dockerfile.server
    command: ["4545", "1000", "1", "2"]
    tty: true
    stdin_open: true
    volumes:
      - ./data/:/usr/src/BlacklistServer/build/data
  blacklist_tests:
    container_name: "blacklist_tests"
    build:
      context: ./src/BlacklistServer
      dockerfile: Dockerfile.tests
    tty: true
    stdin_open: true
    volumes:
      - ./data/:/usr/src/BlacklistServer/build/data

  webserver:
    container_name: "webserver"
    build:
      context: ./src/WebServer
      dockerfile: Dockerfile.webserver
    ports:
      - "8000:8000"

  blacklist_client:
    container_name: "blacklist_client"
    build:
      context: ./src/BlacklistClient
      dockerfile: Dockerfile.client
    command: ["blacklist_server", "4545"]
    tty: true
    stdin_open: true